### PR TITLE
Fix for swallowing unkown errors - fixes #1133

### LINKED ISSUE #1133: Latest refactor of task/cmd/task/task.go is swallowing errors
> Thanks for your bug report!
>
> Before submitting this issue, please make sure the same problem was
> not already reported by someone else.
>
> Please describe the bug you're facing. Consider pasting example
> Taskfiles showing how to reproduce the problem.

- Task version: 3.24.0
- Operating System: MacOS Monterey 12.6

Here's the code:

https://github.com/go-task/task/blob/c2523796c0de468c25b19f49ca257fe43ea470e2/cmd/task/task.go#L46-L54

just need a `log.Fatal(err)` before line 52

I'll send a PR

### PR DESCRIPTION
**Pull request by clintmod**
> Thanks for your pull request, we really appreciate contributions!
>
> Please understand that it may take some time to be reviewed.
>
> Also, make sure to follow the [Contribution Guide](https://taskfile.dev/contributing/).

### CODE REVIEW

File: cmd/task/task.go [hunk 1]
```diff
@@ -49,6 +49,7 @@ func main() {
 			log.Print(err.Error())
 			os.Exit(err.Code())
 		}
+		log.Fatal(err)
```
Comment (pd93) [inline cmd/task/task.go:52]: This should be `log.Print(err.Error())` IMO.

`log.Fatal()` will call `log.Print()` followed by `os.Exit(1)` - which is technically what we want. However, we should stick to exiting with the `errors.CodeUnknown` const that we have defined for clarity.

Comment (clintmod) [reply cmd/task/task.go]: @pd93 fixed

**Review by pd93 — APPROVED** [review]
LGTM 🚀
